# Generated by Django 4.0.5 on 2022-06-14 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_image_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
